---
- name: Install Google Cloud SDK repo
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: "{{ gcp_sdk_yum_repository }}"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ gcp_sdk_gpg_keys }}"
    skip_if_unavailable: yes

- name: Install GCP stuff
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ gcloud_components }}"
